# Generated by Django 4.1 on 2022-08-15 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_comment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='date',
        ),
    ]
